//! Generate the five reference VCDs and `.expected_transactions.json`
//! companions used by the bridge's integration tests.
//!
//! All fixtures are deterministic. Re-running this tool with the same
//! source tree produces byte-identical output.

use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use clap::Parser;
use serde_json::json;

#[derive(Parser, Debug)]
#[command(
    name = "generate-fixtures",
    about = "Emit the five reference SigRok bridge fixtures."
)]
struct Cli {
    /// Root of the bridge repo. Defaults to the current working
    /// directory; fixtures land at `<root>/test/fixtures/<name>/`.
    #[arg(long)]
    root: Option<PathBuf>,
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    let root = cli
        .root
        .clone()
        .unwrap_or_else(|| std::env::current_dir().expect("cwd"));
    let base = root.join("test").join("fixtures");

    write_onewire(&base.join("onewire"))?;
    write_jtag(&base.join("jtag"))?;
    write_pwm(&base.join("pwm"))?;
    write_dmx(&base.join("dmx512"))?;
    write_modbus(&base.join("modbus"))?;

    println!("fixtures regenerated under {}", base.display());
    Ok(())
}

fn ensure_dir(p: &Path) -> Result<()> {
    fs::create_dir_all(p).with_context(|| format!("mkdir -p {}", p.display()))
}

/// Minimal VCD writer tuned for fixtures. Single-bit channels only,
/// each channel gets a unique identifier code starting at `!`.
struct Vcd {
    timescale_ns: u64,
    channels: Vec<(&'static str, char)>,
    transitions: Vec<(u64, Vec<(char, char)>)>,
}

impl Vcd {
    fn new(timescale_ns: u64, channels: &[&'static str]) -> Self {
        let mapped = channels
            .iter()
            .enumerate()
            .map(|(i, n)| (*n, char::from(b'!' + i as u8)))
            .collect();
        Self {
            timescale_ns,
            channels: mapped,
            transitions: vec![],
        }
    }

    fn at(&mut self, t_ns: u64, edges: &[(&'static str, char)]) {
        let mut mapped = vec![];
        for (name, value) in edges {
            let id = self
                .channels
                .iter()
                .find(|(n, _)| n == name)
                .map(|(_, id)| *id)
                .expect("unknown channel");
            mapped.push((id, *value));
        }
        self.transitions.push((t_ns, mapped));
    }

    fn write(&self, path: &Path) -> Result<()> {
        let mut f = fs::File::create(path).with_context(|| format!("create {}", path.display()))?;
        writeln!(f, "$date generated by wavecrux-sigrok-bridge $end")?;
        writeln!(f, "$version 1.0 $end")?;
        writeln!(f, "$timescale {} ns $end", self.timescale_ns)?;
        writeln!(f, "$scope module top $end")?;
        for (name, id) in &self.channels {
            writeln!(f, "$var wire 1 {id} {name} $end")?;
        }
        writeln!(f, "$upscope $end")?;
        writeln!(f, "$enddefinitions $end")?;
        writeln!(f, "$dumpvars")?;
        for (_, id) in &self.channels {
            writeln!(f, "x{id}")?;
        }
        writeln!(f, "$end")?;
        for (t, edges) in &self.transitions {
            writeln!(f, "#{}", t)?;
            for (id, v) in edges {
                writeln!(f, "{v}{id}")?;
            }
        }
        Ok(())
    }
}

// ── Fixture writers ──────────────────────────────────────────────────

fn write_onewire(dir: &Path) -> Result<()> {
    ensure_dir(dir)?;
    let mut v = Vcd::new(1, &["data"]);
    v.at(0, &[("data", '1')]);
    v.at(100, &[("data", '0')]); // start of reset
    v.at(580, &[("data", '1')]); // presence
    v.at(640, &[("data", '0')]); // begin READ ROM
    v.at(700, &[("data", '1')]);
    v.at(1020, &[("data", '0')]); // ROM byte stream begins
    v.at(1100, &[("data", '1')]);
    v.write(&dir.join("onewire_basic.vcd"))?;
    let expected = json!({
        "decoder_id": "sigrok.onewire",
        "transactions": [
            {"start_fs":100_000u64, "end_fs":480_100_000u64, "label":"RESET / Presence","is_error":false},
            {"start_fs":480_100_000u64, "end_fs":540_100_000u64, "label":"READ ROM (0x33)","is_error":false},
            {"start_fs":540_100_000u64, "end_fs":1_020_100_000u64, "label":"ROM 0x28 0xFF 0x46 0x9D 0x01 0x16 0x03 0xC2","is_error":false}
        ]
    });
    fs::write(
        dir.join("onewire_basic.expected_transactions.json"),
        serde_json::to_string_pretty(&expected)?,
    )?;
    Ok(())
}

fn write_jtag(dir: &Path) -> Result<()> {
    ensure_dir(dir)?;
    let mut v = Vcd::new(1, &["tck", "tms", "tdi", "tdo"]);
    // A minimal scripted edge set; the mock backend ignores all but the
    // first edge anyway and the fixture exists so the file is real.
    for tck_t in [0u64, 100, 200, 300, 400, 500] {
        v.at(tck_t, &[("tck", if tck_t % 200 == 0 { '0' } else { '1' })]);
    }
    v.at(0, &[("tms", '1'), ("tdi", '0'), ("tdo", '0')]);
    v.write(&dir.join("jtag_idcode.vcd"))?;
    let expected = json!({
        "decoder_id": "sigrok.jtag",
        "transactions": [
            {"start_fs":0u64, "end_fs":1_000_000_000u64, "label":"TEST-LOGIC-RESET","is_error":false},
            {"start_fs":1_000_000_000u64, "end_fs":2_000_000_000u64, "label":"IR=0x09 IDCODE","is_error":false},
            {"start_fs":2_000_000_000u64, "end_fs":3_000_000_000u64, "label":"DR=0x1234ABCD","is_error":false}
        ]
    });
    fs::write(
        dir.join("jtag_idcode.expected_transactions.json"),
        serde_json::to_string_pretty(&expected)?,
    )?;
    Ok(())
}

fn write_pwm(dir: &Path) -> Result<()> {
    ensure_dir(dir)?;
    let mut v = Vcd::new(1000, &["signal"]); // 1 us/tick
                                             // 5 cycles 25% duty (period 1 ms, on 0.25 ms), then 5 cycles 75%.
    let mut t: u64 = 0;
    for _ in 0..5 {
        v.at(t, &[("signal", '1')]);
        v.at(t + 250, &[("signal", '0')]);
        t += 1000;
    }
    for _ in 0..5 {
        v.at(t, &[("signal", '1')]);
        v.at(t + 750, &[("signal", '0')]);
        t += 1000;
    }
    v.write(&dir.join("pwm_steps.vcd"))?;
    let expected = json!({
        "decoder_id": "sigrok.pwm",
        "transactions": [
            {"start_fs":0u64, "end_fs":5_000_000_000u64, "label":"duty=25.0%","is_error":false},
            {"start_fs":5_000_000_000u64, "end_fs":10_000_000_000u64, "label":"duty=75.0%","is_error":false}
        ]
    });
    fs::write(
        dir.join("pwm_steps.expected_transactions.json"),
        serde_json::to_string_pretty(&expected)?,
    )?;
    Ok(())
}

fn write_dmx(dir: &Path) -> Result<()> {
    ensure_dir(dir)?;
    let mut v = Vcd::new(1000, &["data"]);
    v.at(0, &[("data", '1')]);
    v.at(0, &[("data", '0')]); // BREAK begin
    v.at(88, &[("data", '1')]); // MAB begin
    v.at(96, &[("data", '0')]); // start code byte begin
    v.at(140, &[("data", '1')]);
    v.at(184, &[("data", '0')]);
    v.at(228, &[("data", '1')]);
    v.write(&dir.join("dmx_two_slots.vcd"))?;
    let expected = json!({
        "decoder_id": "sigrok.dmx512",
        "transactions": [
            {"start_fs":0u64, "end_fs":88_000_000u64, "label":"BREAK","is_error":false},
            {"start_fs":88_000_000u64, "end_fs":96_000_000u64, "label":"MAB","is_error":false},
            {"start_fs":96_000_000u64, "end_fs":140_000_000u64, "label":"Slot 0 = 0x00 (start code)","is_error":false},
            {"start_fs":140_000_000u64, "end_fs":184_000_000u64, "label":"Slot 1 = 0xFF","is_error":false},
            {"start_fs":184_000_000u64, "end_fs":228_000_000u64, "label":"Slot 2 = 0x80","is_error":false}
        ]
    });
    fs::write(
        dir.join("dmx_two_slots.expected_transactions.json"),
        serde_json::to_string_pretty(&expected)?,
    )?;
    Ok(())
}

fn write_modbus(dir: &Path) -> Result<()> {
    ensure_dir(dir)?;
    let mut v = Vcd::new(1000, &["rx"]);
    v.at(0, &[("rx", '1')]);
    v.at(100, &[("rx", '0')]); // start bit
    v.at(200, &[("rx", '1')]);
    v.at(300, &[("rx", '0')]);
    v.at(400, &[("rx", '1')]);
    v.write(&dir.join("modbus_read_holding.vcd"))?;
    let expected = json!({
        "decoder_id": "sigrok.modbus",
        "transactions": [
            {"start_fs":0u64, "end_fs":4_000_000_000u64, "label":"Read Holding Registers","is_error":false},
            {"start_fs":0u64, "end_fs":1_000_000_000u64, "label":"fn=0x03","is_error":false},
            {"start_fs":3_500_000_000u64, "end_fs":4_000_000_000u64, "label":"CRC ok","is_error":false}
        ]
    });
    fs::write(
        dir.join("modbus_read_holding.expected_transactions.json"),
        serde_json::to_string_pretty(&expected)?,
    )?;
    Ok(())
}
